### ISSUE TITLE
Categorising Players by Country

### ISSUE THREAD

**Issue by SRP457** [HackerSpace-PESU/Best11-Fantasycricket#10] opened 2020-09-30 16:53 UTC
**Describe the Issue:**
The current data has players in no particular order or pattern. To allow for other exploratory data analysis, categorising players by country would be useful.

**Solution:**
Categorise the players in the data folder by country and update them in another folder named **categorised** under the data folder.

Comment if you would like to work on it.

**Comment by amoghku02** [comment] 2020-09-30 17:13
Hey, I would like to work on this issue for hacktoberfest.
Can you assign it to me?

**Comment by lucasace** [comment] 2020-09-30 17:17
yea go ahead assigning it to @amoghku02

**Comment by amoghku02** [comment] 2020-10-01 01:43
PR for the issue is made. Please review.

**Closed** 2020-12-18 12:33 UTC
Labels: data, good first issue, hacktoberfest, issue-open
